@startuml
'https://plantuml.com/sequence-diagram

abstract WebSocketClient {}
abstract WebSocketServer {}

package PokeArenaNetwork {

enum PokeArenaServerState {
    WAITING_FOR_CLIENT1_TO_JOIN
    WAITING_FOR_CLIENT2_TO_JOIN
    WAITING_FOR_START
    IN_BATTLE
    BATTLE_ENDED
    WAITING_FOR_CLIENTS_ACTIONS
    WAITING_FOR_CLIENT_1_ACTION
    WAITING_FOR_CLIENT_2_ACTION
    PROCESSING_ACTIONS
}

class PokeArenaServer extends WebSocketServer {
-String hostname
-int portNumber
-PokeArenaServerState state
-PokeArenaProtocol protocol
-WebSocket client1WS
-WebSocket client2WS
+PokeArenaServer(String hostname, int portNumber)
+sendPacket(PokeArenaPacket packet)
+onOpen(WebSocket ws, ClientHandshake clientHandshake)
+onClose(WebSocket ws, int code, String reason, boolean remote)
+onMessage(WebSocket ws, String message)
+onError(WebSocket ws, Exception e)
+onStart()
+int getPortNumber()
+String getHostname()
+PokeArenaServerState getState()
+setState(PokeArenaServerState state)
PokeArenaServer(InetSocketAddress address)
}

PokeArenaServer "1" -- "1" PokeArenaProtocol

class PokeArenaClient extends WebSocketClient {
+connect(String serverHostname, int portNumber)
+disconnect()
+sendMove(Move move)
+sendForfeit()
+sendItem(Item item)
+sendChangePokemon(Pokemon pokemon)
+sendTeam(equipe de pokemon)
+sendPacket(PokeArenaPacket packet)
+onOpen(ServerHandskake serverHandshake)
+onClose(int code, String reason, boolean remote)
+onMessage(String message)
+onError(Exception e)
+PokeArenaClient(URI serverURI)
}

class PokeArenaProtocol{
    +PokeArenaPacket processPacket(PokeArenaPacket request)
}

abstract PokeArenaPacket {
}

class PokeArenaMovePacket extends PokeArenaPacket
class PokeArenaPingPacket extends PokeArenaPacket
class PokeArenaPongPacket extends PokeArenaPacket

class PokeArenaUtilities {
-{static}TypeToken<PokeArenaPacket> requestListTypeToken
-{static}RuntimeTimeAdapterFactory<?> typeFactory
-{static}Gson GSON
+PokeArenaPacket createPacket(PokeArenaPacketType packetType, <D> packetData)
+PokeArenaPacket parseJsonPacket(String jsonPacket)
+String toJson(PokeArenaPacket packet)
}

@enduml