package Controller;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import java.net.URL;
import java.util.ResourceBundle;

import javafx.beans.value.ChangeListener;
import javafx.beans.value.ObservableValue;
import javafx.event.ActionEvent;

import javafx.scene.layout.AnchorPane;

import javafx.scene.control.ChoiceBox;

public class MenuTeamController implements Initializable {
	@FXML
	private AnchorPane menuSet;
	@FXML
	private ChoiceBox<String> nbList;
	@FXML
	private TextField p1;
	@FXML
	private TextField p2;
	@FXML
	private TextField p3;
	@FXML
	private TextField p4;
	@FXML
	private TextField p5;
	@FXML
	private TextField p6;
	@FXML
	private Button addButton;
	@FXML
	private TextField teamNameField;
	@FXML
	private Button suppButton;

	// Event Listener on Button[#addButton].onAction
	@FXML
	public void handleAddButton(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#suppButton].onAction
	@FXML
	public void handleSuppButton(ActionEvent event) {
		// TODO Autogenerated
	}
	@Override
	public void initialize(URL location, ResourceBundle resources) {
		// TODO Auto-generated method stub
		nbList.getItems().clear();
		nbList.getItems().addAll("3 Pokemons", "6 Pokemons");
		nbList.getSelectionModel().select("3 Pokemons");

		nbList.getSelectionModel().selectedIndexProperty().addListener(new ChangeListener<Number>() {

			@Override
			public void changed(ObservableValue<? extends Number> observable, Number oldValue, Number newValue) {
				System.out.println(newValue.toString());
				//TODO si value 3Poke alors desactiver et griser p4 à p6

			}
		});
		

	}
}
