package application.Controller;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.layout.AnchorPane;

import javafx.scene.control.ChoiceBox;

public class MenuMultiController {
	@FXML
	private AnchorPane menuSolo;
	@FXML
	private Label labelChooseTeam;
	@FXML
	private ChoiceBox<?> modeList;
	@FXML
	private ChoiceBox<?> teamList;
	@FXML
	private Button hostButton;
	@FXML
	private TextField ipField;
	@FXML
	private Button joinButton;

	// Event Listener on Button[#hostButton].onAction
	@FXML
	public void handleHostButton(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#joinButton].onAction
	@FXML
	public void handleJoinButton(ActionEvent event) {
		// TODO Autogenerated
	}
}
